import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:firebase_analytics/firebase_analytics.dart';

/// Firebase service wrapper for easy initialization and access
class FirebaseService {
  // Singleton instance
  static FirebaseService? _instance;
  
  // Firebase instances (nullable until initialized)
  FirebaseAuth? _auth;
  FirebaseFirestore? _firestore;
  FirebaseMessaging? _messaging;
  FirebaseAnalytics? _analytics;
  
  bool _initialized = false;
  
  // Private constructor
  FirebaseService._();
  
  /// Get singleton instance
  static FirebaseService get instance {
    _instance ??= FirebaseService._();
    return _instance!;
  }
  
  /// Check if Firebase is initialized
  bool get isInitialized => _initialized;
  
  /// Safe accessors that throw if not initialized
  FirebaseAuth get auth => _auth ?? (throw StateError('Firebase not initialized'));
  FirebaseFirestore get firestore => _firestore ?? (throw StateError('Firebase not initialized'));
  FirebaseMessaging get messaging => _messaging ?? (throw StateError('Firebase not initialized'));
  FirebaseAnalytics get analytics => _analytics ?? (throw StateError('Firebase not initialized'));
  
  /// Initialize Firebase
  /// 
  /// Call this in main.dart before runApp()
  /// Requires firebase_options.dart generated by FlutterFire CLI
  Future<void> initialize() async {
    if (_initialized) return;
    
    try {
      // Initialize instances
      _auth = FirebaseAuth.instance;
      _firestore = FirebaseFirestore.instance;
      _messaging = FirebaseMessaging.instance;
      _analytics = FirebaseAnalytics.instance;
      
      // Request notification permissions
      await _requestNotificationPermissions();
      
      // Enable Firestore offline persistence
      _firestore!.settings = const Settings(
        persistenceEnabled: true,
        cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
      );
      
      _initialized = true;
      debugPrint('✅ Firebase services initialized');
    } catch (e) {
      debugPrint('❌ Firebase service initialization failed: $e');
      // Reset all to null on failure
      _auth = null;
      _firestore = null;
      _messaging = null;
      _analytics = null;
      _initialized = false;
    }
  }
  
  Future<void> _requestNotificationPermissions() async {
    if (_messaging == null) return;
    try {
      final settings = await _messaging!.requestPermission(
        alert: true,
        badge: true,
        sound: true,
      );
      debugPrint('📬 Notification permission: ${settings.authorizationStatus}');
    } catch (e) {
      debugPrint('⚠️ Notification permission request failed: $e');
    }
  }
  
  // ============ Auth Methods ============
  
  /// Get current user (null if not logged in)
  User? get currentUser => _auth?.currentUser;
  
  /// Stream of auth state changes
  Stream<User?> get authStateChanges => _auth?.authStateChanges() ?? Stream.value(null);
  
  /// Sign in with email/password
  Future<UserCredential> signInWithEmail({
    required String email,
    required String password,
  }) async {
    return await auth.signInWithEmailAndPassword(
      email: email,
      password: password,
    );
  }
  
  /// Create account with email/password
  Future<UserCredential> createAccount({
    required String email,
    required String password,
  }) async {
    return await auth.createUserWithEmailAndPassword(
      email: email,
      password: password,
    );
  }
  
  /// Sign in anonymously
  Future<UserCredential> signInAnonymously() async {
    return await auth.signInAnonymously();
  }
  
  /// Sign out
  Future<void> signOut() async {
    await auth.signOut();
  }
  
  // ============ Firestore Methods ============
  
  /// Get document reference
  DocumentReference doc(String path) => firestore.doc(path);
  
  /// Get collection reference
  CollectionReference collection(String path) => firestore.collection(path);
  
  // ============ Analytics Methods ============
  
  /// Log custom event
  Future<void> logEvent({
    required String name,
    Map<String, Object>? parameters,
  }) async {
    await analytics.logEvent(name: name, parameters: parameters);
  }
  
  /// Log screen view
  Future<void> logScreenView(String screenName) async {
    await analytics.logScreenView(screenName: screenName);
  }
}

/// Riverpod provider for FirebaseService
final firebaseServiceProvider = Provider<FirebaseService>((ref) {
  return FirebaseService.instance;
});

/// Provider for auth state stream
final authStateProvider = StreamProvider<User?>((ref) {
  final firebase = ref.watch(firebaseServiceProvider);
  if (!firebase.isInitialized) {
    return Stream.value(null);
  }
  return firebase.authStateChanges;
});

/// Provider for current user
final currentUserProvider = Provider<User?>((ref) {
  final authState = ref.watch(authStateProvider);
  return authState.valueOrNull;
});

