// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// IMPORTANT: Replace the placeholder values below with your actual 
/// Firebase project configuration. You can get these values from:
/// 1. Go to Firebase Console (https://console.firebase.google.com)
/// 2. Select your project
/// 3. Click the gear icon > Project settings
/// 4. Scroll to "Your apps" section
/// 5. Click the Flutter icon or add a new app
/// 6. Copy the configuration values
///
/// Alternatively, run: `flutterfire configure` to auto-generate this file.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase Web configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCDEF0123456789GHIJKLMNOPQRSTU',
    appId: '1:123456789012:web:abcdef123456789012ab',
    messagingSenderId: '123456789012',
    projectId: 'waitless-placeholder',
    authDomain: 'waitless-placeholder.firebaseapp.com',
    storageBucket: 'waitless-placeholder.appspot.com',
  );

  // TODO: Replace with your actual Firebase Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABCDEF0123456789GHIJKLMNOPQRSTU',
    appId: '1:123456789012:android:abcdef123456789012',
    messagingSenderId: '123456789012',
    projectId: 'waitless-placeholder',
    storageBucket: 'waitless-placeholder.appspot.com',
  );

  // TODO: Replace with your actual Firebase iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABCDEF0123456789GHIJKLMNOPQRSTU',
    appId: '1:123456789012:ios:abcdef1234567890abcd',
    messagingSenderId: '123456789012',
    projectId: 'waitless-placeholder',
    storageBucket: 'waitless-placeholder.appspot.com',
    iosBundleId: 'com.waitless.waitless',
  );

  // TODO: Replace with your actual Firebase macOS configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.waitless',
  );

  // TODO: Replace with your actual Firebase Windows configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:web:YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}
